version: "2"
services:
  elasticsearch:
    image: elasticsearch:7.12.0
    command: elasticsearch -Des.network.host=0.0.0.0
  kibana:
    image: diamol/kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  logstash:
    image: szpaczyn/logstash-arm64:v7.12.0
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash:/etc/logstash/conf.d
      - ./logstash/patterns:/opt/logstash/patterns
    depends_on:
      - elasticsearch
  filebeat:
    image: prima/filebeat
    volumes:
      - ./filebeat/filebeat.yml:/filebeat.yml
      - ../fake-logs:/var/log
    depends_on:
      - logstash
